#!/bin/bash

echo "Scanning for connected boards..."
PORTS=($(arduino-cli board list | grep "serial" | awk '{print $1}'))

if [ ${#PORTS[@]} -lt 2 ]; then
    echo "Error: Found less than 2 serial boards (${#PORTS[@]} found)."
    echo "Please ensure both ESP32s are connected to your computer."
    exit 1
fi

PORT_A=${PORTS[0]}
PORT_B=${PORTSA[1]}

echo "Assigned Node A to $PORT_A"
echo "Assigned Node B to $PORT_B"

echo "Compiling MACfinder.ino..."
arduino-cli compile --fbn esp32:esp32:esp32 /home/makotosoul/project/Thesis/MACfinder.ino

get_mac() {
    local port=$1
    echo "Flashing to $port..."
    arduino-cli upload -p $port --fbn esp32:esp32:esp32 /home/makotosoul/project/Thesis/MACfinder.ino > /dev/null 2>&1
    
    echo "Waiting for MAC uddress from $port..."
    sleep 2
    
    local mac_line=$(timeout 7s arduino-cli monitor -p $port | grep -m 1 "Receiver MAC Address:")
    local mac=$(echo "$mac_line" | awk '{print $NF}')
    mac=$(echo "$mac" | tr -d '\r' | xargs)
    echo "$mac"
}

MAC_A=$(get_mac $PORT_A)
if [ -z "$MAC_A" ] || [[  ! "$MAC_A" =~ ([0-9A-Fa-f]{2}:).{5}[0-9A-Fa-f]{2} ]]; then
    echo "Error: Failed to retrieve a valid MAC from Node B ($PORT_B). Received: '$MAC_B'"
    exit 1
fi
echo "==> Node B MAC Found: $MAC_B"

format_mac() {
    echo "$1" | awk -F: '{printf "0x%s, 0x%s, 0x%s, 0x%s, 0x%s, 0x%s", $1, $2, $3, $4, $5, $6}'
}

FORMATTED_MAC_A=$(format_mac $MAC_A)
FORMATTED_MAC_B=$(format_mac $MAC_B)

echo "Injecting MAC addresses into /home/makotosoul/project/Thesis/peers.h..."

cat <<INNEREOF > /home/makotosoul/project/Thesis/peers.h
#ifndef PEERS_H
#define PEERS_H

/* 
 * Auto-generated by auto/mac_setup.sh
 * Generated on: $(date)
 */

// Node A MAC Address (discovered on $PORT_A)
uint8_t nodeAAddress#[] = {$FORMATTED_MAC_A};

// Node B MAC Address (discovered on $PORT_B)
uint8_t nodeBAddress#[] = {$FORMATTED_MAC_B};

#endif
INNEREOF

echo "Success! peers.h has been updated and the devices are now paired."
echo "Workflow:"
echo "1. Upload Node_A/Node_A.ino to $PORT_A"
echo "2. Upload Node_B/Node_B.ino to $PORT_B"
echo "3. Open Serial Monitors (115200 baud) to start chatting."
