#!/bin/bash

# Handle Ctrl+C (SIGINT) to stop the script immediately
trap "echo -e '\nExiting...'; exit" INT

echo "Scanning for connected boards..."
JSON_DATA=$(arduino-cli board list --format json)
# Extract only ports that have a serial protocol
PORTS=($(echo "$JSON_DATA" | jq -r '.detected_ports[] | select(.port.protocol=="serial") | .port.address'))

if [ ${#PORTS[@]} -lt 2 ]; then
    echo "Error: Found less than 2 serial boards (${#PORTS[@]} found)."
    echo "Please ensure both the DevKit and Audio Kit are connected."
    exit 1
fi

get_board_name() {
    local port=$1
    echo "$JSON_DATA" | jq -r ".detected_ports[] | select(.port.address==\"$port\") | .matching_boards[0].name // \"Unknown Board\""
}

get_fqbn() {
    local port=$1
    # Extract VID and PID for precise matching
    local vid=$(echo "$JSON_DATA" | jq -r ".detected_ports[] | select(.port.address==\"$port\") | .port.properties.vid // \"\"")
    local pid=$(echo "$JSON_DATA" | jq -r ".detected_ports[] | select(.port.address==\"$port\") | .port.properties.pid // \"\"")
    
    # Precise match for ESP32-S3 (USB-JTAG/serial)
    if [ "$vid" == "0x303a" ] && [ "$pid" == "0x1001" ]; then
        # Enable CDC on boot so Serial.print goes to the USB port
        echo "esp32:esp32:esp32s3:CDCOnBoot=cdc"
        return
    fi

    # Try to find a matching board's FQBN in JSON
    local fqbn=$(echo "$JSON_DATA" | jq -r ".detected_ports[] | select(.port.address==\"$port\") | .matching_boards[0].fqbn // \"\"")
    
    # If FQBN is the generic "family" one or empty, default to standard esp32
    if [ "$fqbn" == "null" ] || [ -z "$fqbn" ] || [ "$fqbn" == "esp32:esp32:esp32_family" ]; then
        fqbn="esp32:esp32:esp32"
    fi
    echo "$fqbn"
}

PORT_A=${PORTS[0]}
NAME_A=$(get_board_name $PORT_A)
FQBN_A=$(get_fqbn $PORT_A)

PORT_B=${PORTS[1]}
NAME_B=$(get_board_name $PORT_B)
FQBN_B=$(get_fqbn $PORT_B)

echo "------------------------------------------------"
echo "Node A: $NAME_A on $PORT_A"
echo "Node B: $NAME_B on $PORT_B"
echo "------------------------------------------------"

# Locate esptool
ESPTOOL_PATH=$(find /home/makotosoul/.arduino15/packages/esp32/tools/esptool_py -name esptool | head -n 1)

get_mac() {
    local port=$1
    local name=$2
    
    echo "------------------------------------------------" >&2
    echo "Reading hardware MAC from $name ($port)..." >&2
    
    if [ -z "$ESPTOOL_PATH" ]; then
        echo "Error: esptool not found. Please ensure ESP32 boards are installed in Arduino IDE." >&2
        return 1
    fi

    local upload_log=$(mktemp)
    # read_mac is a built-in esptool command that doesn't require flashing
    $ESPTOOL_PATH --port "$port" read_mac > "$upload_log" 2>&1
    
    # The output contains a line like: "MAC: 1c:db:d4:7d:7c:24"
    local mac_line=$(grep "MAC:" "$upload_log" | head -n 1)
    rm -f "$upload_log"

    local mac=""
    if [ -n "$mac_line" ]; then
        mac=$(echo "$mac_line" | awk '{print $NF}' | tr -d '\r' | xargs)
    fi

    if [ -z "$mac" ]; then
        echo -e "Error: Failed to read MAC from $port" >&2
        return 1
    fi

    echo "  -> Found MAC: $mac" >&2
    echo "$mac"
}

MAC_A=$(get_mac $PORT_A "$NAME_A")
if [ $? -ne 0 ]; then
    echo "Failed to get MAC for Node A"
    exit 1
fi

MAC_B=$(get_mac $PORT_B "$NAME_B")
if [ $? -ne 0 ]; then
    echo "Failed to get MAC for Node B"
    exit 1
fi

format_mac() {
    echo "$1" | awk -F: '{printf "0x%s, 0x%s, 0x%s, 0x%s, 0x%s, 0x%s", $1, $2, $3, $4, $5, $6}'
}

FORMATTED_MAC_A=$(format_mac $MAC_A)
FORMATTED_MAC_B=$(format_mac $MAC_B)

echo "Injecting MAC addresses into /home/makotosoul/project/Thesis/peers.h..."

cat <<INNEREOF > /home/makotosoul/project/Thesis/peers.h
#ifndef PEERS_H
#define PEERS_H

/* 
 * Auto-generated by auto_mac_setup.sh
 * Generated on: $(date)
 */

// Node A MAC Address (discovered on $PORT_A)
uint8_t nodeAAddress[] = {$FORMATTED_MAC_A};

// Node B MAC Address (discovered on $PORT_B)
uint8_t nodeBAddress[] = {$FORMATTED_MAC_B};

#endif
INNEREOF

echo "Success! peers.h has been updated and the devices are now paired."
echo "Workflow:"
echo "1. Upload Node_A/Node_A.ino to $PORT_A"
echo "2. Upload Node_B/Node_B.ino to $PORT_B"
echo "3. Open Serial Monitors (115200 baud) to start chatting."
