#ifndef PEERS_H
#define PEERS_H

/* 
 * Auto-generated by auto_mac_setup.sh
 * Generated on: Wed Apr 29 05:58:17 PM EEST 2026
 */

// Node A MAC Address (discovered on /dev/ttyACM0)
uint8_t nodeAAddress[] = {0x1c, 0xdb, 0xd4, 0x7d, 0x7c, 0x24};

// Node B MAC Address (discovered on /dev/ttyUSB0)
uint8_t nodeBAddress[] = {0xe0, 0x8c, 0xfe, 0x63, 0xff, 0x28};

#endif
