#ifndef PEERS_H
#define PEERS_H

/*
 * Auto-generated by auto_mac_setup.sh
 *
 * Raw MAC byte macros — use these to initialise arrays with any name/qualifiers.
 * Run ./auto_mac_setup.sh with both boards plugged in to update.
 */

#define PEER_MAC_A  0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF
#define PEER_MAC_B  0xEE, 0xEE, 0xEE, 0xEE, 0xEE, 0xEE

/* Arduino-compatible arrays (Node_A, Node_B, Node_A_Audio, Node_B_Audio) */
static const uint8_t nodeAAddress[] = {PEER_MAC_A};
static const uint8_t nodeBAddress[] = {PEER_MAC_B};

#endif
