dependencies:
  idf: '>=4.4'
description: Opus audio codec library for ESP32 - high-quality audio compression with
  ESP-IDF optimizations
license: Apache-2.0
maintainers:
- Kevin Ahrendt <kevin.ahrendt@openhomefoundation.org>
repository: git://github.com/esphome-libs/micro-opus.git
repository_info:
  commit_sha: 8354085908683c6130e32a832aeec8a7ca115c51
  path: .
url: https://github.com/esphome-libs/micro-opus
version: 0.4.1
